### ISSUE TITLE
Use a new icon

### ISSUE THREAD

**Issue by robinpaulson** [red-coracle/episodes#12]
Anything, so long as it's different from the original. Combined with using the same name, it's very difficult to tell the two apart.

**Comment by red-coracle** [comment]
I'm not very artistic, but here are some icons I found that are vaguely television-related and had licenses that should be compatible: https://imgur.com/a/KI5xiIT

Input from anyone on a preferred choice or a better icon is welcome! 🙂

**Comment by robinpaulson** [comment]
The third icon says "movies" to me, rather than TV shows.

The fourth icon is the icon for mplayer (i think, or perhaps it's another UNIXY video player) so it's probably best to avoid that.

The fifth icon makes me think of a computer monitor, not TV shows.

Both of the remaining candidates are good; personally I prefer the first, for contrast reasons.

**Comment by red-coracle** [comment]
I did a reverse image search on the first and it looks like there's at least one other app using the same icon. I adjusted the second to have similar colours and put together a few more options: https://imgur.com/a/pReh0IU
