### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [red-coracle/episodes#13]
Can the app be translated? With something like weblate, poeditor, crowdin or transifex.

**Comment by red-coracle** [comment]
The app can be translated by copying [strings.xml](https://github.com/red-coracle/episodes/blob/master/app/src/main/res/values/strings.xml) to a new folder like `values-de` and then translating there.

I'm not sure it's worth setting up a separate service for it yet, but I'll look into it.

**Comment by comradekingu** [comment]
@red-coracle It really is beneficial, not only does it lower the barrier of entry to contributing, keeping things up-to-date, but it is also easier to spot mistakes in the source strings with more eyeballs.

https://hosted.weblate.org/hosting/ is what I like the best, having used all of the above.

Hosted Weblate already has https://hosted.weblate.org/projects/tinymediamanager/ and a lot of Android apps, like NewPipe.

**Comment by robinpaulson** [comment]
@comradekingu Thanks for that, I didn't know weblate had a hosted edition. We'll check this out for a project I maintain, [forecastie](https://github.com/martykan/forecastie/).

**Comment by robinpaulson** [comment]
It appears hosted weblate requires either money or a "negotiation" with the site owners. Still interesting and useful, but a bit of a barrier.

**Comment by comradekingu** [comment]
You can't have it both ways. It can't be both a service that costs something to run _and_ an unlimited offer in every capacity. There has to be some limit, albeit that is fairly theoretical. It doesn't have a shady model,and I have never seen an eligible libre software project turned down for gratis hosting. What's not to like? It is a profitable, but not lucrative business, and has had a lot of projects on for quite some time.

If money is the barrier, and I don't see how it could be, you can still self-host Weblate.

**Comment by robinpaulson** [comment]
> If money is the barrier, and I don't see how it could be

Sure, everyone has spare money to throw around. We're all as rich as you, you glib nitwit.

Also, thanks for the lesson in basic finance, it was hardly patronising at all.

**Comment by comradekingu** [comment]
Seeing as the only requirement is for the license to be libre, is what I meant. The "negotiation" is just a safeguard against it being a promise one can't deliver on. Hosted or self-hosting is gratis at both ends.
Self-hosting obviously incurring other costs. Weblate I imagine knows exactly what it is like to be a small libre software project with only hard work to drive it, because it was, and still is, which I assume is why it gives away hosting.
It isn't any more cynic than helping the ecosystem, and looking good doing it.
With all the money in the world, I would still recommend Weblate.

I figure myself more of Qt library nitwit, but I am open to other interpretations.

**Comment by red-coracle** [comment]
I've submitted a request to Weblate about hosting and will wait to see what they come back with.

**Comment by red-coracle** [comment]
Weblate was backed up for several months and just revamped their libre hosting process. The project for this app should be available here now:
https://hosted.weblate.org/settings/episodes

**Comment by comradekingu** [comment]
@red-coracle I think you have to make it public first. Lots of projects added just now, so get in early :)

**Comment by mondlicht-und-sterne** [comment]
@comradekingu oh nice i can start to translate

**Comment by AIvar0** [comment]
@red-coracle 
Spanish translation added.

**Comment by red-coracle** [comment]
Thanks everyone! I've tagged the next release, so it ought to show up in F-Droid soon.

**Comment by jakubfabijan** [comment]
I added Esperanto on weblate, but when i wanted to start translating, this happend:
![screenshot](https://user-images.githubusercontent.com/53099243/107623555-cf418980-6c59-11eb-911b-c450702a4ea4.png)

**Comment by red-coracle** [comment]
It may be an issue with Weblate because I tried creating the translation as well and it had the same result. I contacted Weblate and will see what they say.
