### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by robinpaulson** [red-coracle/episodes#2]
Hi, we talked some while ago about developing a fork of episodes. Have you been able to make any progress? It'd be good to push it forward, even if only a little for now, perhaps get a release in f-droid?

Cheers

**Comment by red-coracle** [comment]
Hey, so I think I got bogged down with trying to implement UI updates and then I never picked back up on it. I can definitely start on an F-Droid release at the very least.

**Comment by robinpaulson** [comment]
Yep, that would be great. Even if it's only slightly different to the original release.

By the way, did you settle on a name, I think it's important to have something different to the original, so they can be easily distinguished.

**Comment by robinpaulson** [comment]
It's great to see the new release. I'm not entirely sure what the second point on the release notes means. Perhaps there is an unnecessary word in there? Cheers

**Comment by red-coracle** [comment]
Thanks, there was a stray preposition.

Regarding a new name, I haven't decided on anything in particular but I'll be sure to update before submitting to F-Droid.

**Comment by red-coracle** [comment]
An inclusion request is open here: https://gitlab.com/fdroid/fdroiddata/merge_requests/6127

**Comment by robinpaulson** [comment]
It appears to have the same name, that makes it a little more difficult to distinguish between this and the original.

**Comment by LeSpocky** [comment]
> It appears to have the same name, that makes it a little more difficult to distinguish between this and the original.

Yes, but would it make upgrade easier? Or is that not intended?

**Comment by robinpaulson** [comment]
> Yes, but would it make upgrade easier?

Hell no, we shouldn't do that!

This is a fork of the original code; new maintainer, new repo. The user should explicitly be aware the code has been forked and they are installing a different piece of software. The f-droid maintainers will (rightly) not allow re-use of an existing package code anyway.

**Comment by LeSpocky** [comment]
> This is a fork of the original code; new maintainer, new repo. The user should explicitly be aware the code has been forked and they are installing a different piece of software. The f-droid maintainers will (rightly) not allow re-use of an existing package code anyway.

Well, will there be an option to import the old data, like episodes already watched?

**Comment by red-coracle** [comment]
> It appears to have the same name, that makes it a little more difficult to distinguish between this and the original.

TBH I couldn't decide on a name I liked and then I forgot about it. I'll try for next release.

> Well, will there be an option to import the old data, like episodes already watched?

I think you should be able to backup from the old app and restore into the new one. The backup location changed so you'll need to copy to the new directory after backing up.

**Comment by robinpaulson** [comment]
I think there's a problem with the build, when I view the package page on fdroid.org, i get a 404:
https://f-droid.org/en/packages/com.redcoracle.episodes

It should look more like this page:
https://f-droid.org/en/packages/org.jamienicol.episodes/

It's been 7 or 8 days since your metadata changes were accepted, that's usually more than enough for the package to build.

**Comment by robinpaulson** [comment]
And now it's working, installing as I type

**Comment by robinpaulson** [comment]
Closing, my original question is answered

**Comment by LeSpocky** [comment]
> > Well, will there be an option to import the old data, like episodes already watched?
> 
> I think you should be able to backup from the old app and restore into the new one. The backup location changed so you'll need to copy to the new directory after backing up.

That worked quite well. Thank you. 😊
