### ISSUE TITLE
Shows are not updating with new episodes

### ISSUE THREAD

**Issue by pvlnglv** [red-coracle/episodes#22]
I've had this issue for a few weeks now. Whenever I try to refresh the shows, it gets stuck on the first one.

I have tried rebooting, reinstalling.. didn't help.

**Comment by pvlnglv** [comment]
Just in case - I'm on 13.2, getting it through f-droid.

**Comment by red-coracle** [comment]
What is the name of the show it gets stuck on? I tried just now and it's working for me, but it could be specific to a show.

**Comment by pvlnglv** [comment]
It gets stuck on on the first show on the list alphabetically. for me this is American Gods. however, if I remove American Gods from my list, it still gets stuck on the first show, but now it's something else.

**Comment by SH4d0w97** [comment]
> What is the name of the show it gets stuck on? I tried just now and it's working for me, but it could be specific to a show.

I am also having the same issue of shows not updating on v o.13.2.

Money Heist Season 4 is already out but in the app is still stuck at Season 2.

**Comment by SebiderSushi** [comment]
This is what i see in the logcat when i try to update all shows:
```
05-08 17:21:51.592  6569  6609 I org.jamienicol.episodes.RefreshShowUtil: Updating episode 853.
05-08 17:21:51.593  6569  6609 E SQLiteLog: (1) no such column: language
05-08 17:21:51.593  6569  6609 W System.err: android.database.sqlite.SQLiteException: no such column: language (code 1 SQLITE_ERROR): , while compiling: UPDATE episodes SET overview=?,episode_number=?,show_id=?,tvdb_id=?,name=?,season_number=?,language=? WHERE _id=853
05-08 17:21:51.594   548   548 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
05-08 17:21:51.595   548   548 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
05-08 17:21:51.603  6569  6609 W System.err:    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
05-08 17:21:51.603  6569  6609 W System.err:    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:941)
05-08 17:21:51.603  6569  6609 W System.err:    at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:552)
05-08 17:21:51.603  6569  6609 W System.err:    at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
05-08 17:21:51.603  6569  6609 W System.err:    at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
05-08 17:21:51.603  6569  6609 W System.err:    at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
05-08 17:21:51.603  6569  6609 W System.err:    at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1676)
05-08 17:21:51.603  6569  6609 W System.err:    at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1624)
05-08 17:21:51.603  6569  6609 W System.err:    at org.jamienicol.episodes.db.ShowsProvider.update(ShowsProvider.java:283)
05-08 17:21:51.603  6569  6609 W System.err:    at android.content.ContentProvider$Transport.update(ContentProvider.java:361)
05-08 17:21:51.603  6569  6609 W System.err:    at android.content.ContentResolver.update(ContentResolver.java:1721)
05-08 17:21:51.603  6569  6609 W System.err:    at org.jamienicol.episodes.RefreshShowUtil.updateEpisodes(RefreshShowUtil.java:138)
05-08 17:21:51.603  6569  6609 W System.err:    at org.jamienicol.episodes.RefreshShowUtil.refreshShow(RefreshShowUtil.java:56)
05-08 17:21:51.604  6569  6609 W System.err:    at org.jamienicol.episodes.services.RefreshAllShowsTask.call(RefreshAllShowsTask.java:55)
05-08 17:21:51.604  6569  6609 W System.err:    at org.jamienicol.episodes.services.RefreshAllShowsTask.call(RefreshAllShowsTask.java:20)
05-08 17:21:51.604  6569  6609 W System.err:    at org.jamienicol.episodes.services.AsyncTask.lambda$executeAsync$0(AsyncTask.java:13)
05-08 17:21:51.604  6569  6609 W System.err:    at org.jamienicol.episodes.services.-$$Lambda$AsyncTask$lpIRC5B-VlJgMjBVxWmTFiaVmtw.run(Unknown Source:2)
05-08 17:21:51.604  6569  6609 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-08 17:21:51.604  6569  6609 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-08 17:21:51.604  6569  6609 W System.err:    at java.lang.Thread.run(Thread.java:764)                                       
```

Note that my database comes from the old `org.jamienicol.episodes` version code `12` from F-Droid.
If i recall correctly i have used the built-in "Backup Library" feature from Episodes, however i _might_ have forcefully placed the old database in Episodes data folder with root acceess.

**Comment by SebiderSushi** [comment]
Alsp, despite of this crash log the progress notification remains ("stuck at the first show") and can be dismissed.

**Comment by red-coracle** [comment]
> 
> I am also having the same issue of shows not updating on v o.13.2.
> 
> Money Heist Season 4 is already out but in the app its still stuck at Season 2.

@SH4d0w97 I think that's because TheTVDB presents it as only 2 seasons for the aired order, assuming [this](https://www.thetvdb.com/series/la-casa-de-papel) is the one you mean.


@SebiderSushi Thanks for the log. I think this is because the `org.jamienicol.episodes` app diverged from mine. My version added the language to [shows and episodes](https://github.com/red-coracle/episodes/commit/3947b9adbbb3d708a366a59d22b7ff0e9c05dd43) in db version 6, but upstream only [added to the shows table](https://github.com/jamienicol/episodes/commit/f09781851f3683194c43e4f3997a55f0a1007bc9). I'll put something to update the table if that column doesn't exist in order to ease migration. Meanwhile, adding that column to a backup manually and reimporting should work, e.g. 
`sqlite3 episodes.db "ALTER TABLE episodes ADD COLUMN language TEXT;"`

**Comment by pvlnglv** [comment]
I noticed the activity in this thread and decided to try using the app again. Same behavior as before, still getting stuck on the first show it tries to update. It seems to go alphabetically because it's always the one atn the top of the list

If I remove the snow in question, the next one on the list is where it gets stuck on.

**Comment by SebiderSushi** [comment]
There is still no release targeting this issue so no change can be expected. But if you can use a command line or any other way of manipulating sqlite3 databases then you can apply the fix mentioned by @red-coracle, which worked splendid for me by the way, thank you very much!
