### ISSUE TITLE
Replace TheTVDB with TMDb

### ISSUE THREAD

**Issue by red-coracle** [red-coracle/episodes#43]
TheTVDB is planning to charge for API access without any apparent exclusions for open-source/non-commercial use. Ideally there would be a migration to link existing shows/episodes to their equivalent on TMDb.

See UweTrottmann/SeriesGuide#762 for similar discussion.

**Comment by mid-kid** [comment]
Is it somehow possible to migrate while keeping the same shows?

**Comment by red-coracle** [comment]
It will keep the shows and try to match based on ID or season/episode number when you refresh. For testing you can export/import a backup to simulate the upgrade.
