### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by mid-kid** [red-coracle/episodes#52]
When I search for "Great Pretender" in the app, the app doesn't return anything, despite the webside doing so just fine: https://thetvdb.com/search?query=great+pretender

Going to the website, taking note of the series ID, and searching *that* in the app does work, but isn't exactly the most convenient method.

Additionally, it'd be nice to get any indication when a search fails for any reason, including "no results". I end up staring at a white screen hoping for the results to appear for longer than I'm comfortable doing.

**Comment by abirke** [comment]
Hi @mid-kid,

I think the search yielding no results comes down to an encoding problem in the query. I created a pull request #53 that fixes it from my point of view. Maybe you can test the change, too.

The UI change, however, is a second problem I think, which I don't have an immediate solution to.

Best
André

**Comment by mid-kid** [comment]
I don't know how android apps are compiled so I won't be testing it anytime soon, but thanks for trying to solve it - I'll see if it works with the next update.

**Comment by red-coracle** [comment]
I don't have access to my build machine at the moment, but the changes look good to me. I'll try to have the new release made this weekend.

**Comment by abirke** [comment]
Hi everyone,

the fix should now be available from f-droid. Thanks for looking into it so quickly, @red-coracle!

**Comment by mid-kid** [comment]
Can confirm it works now. Thanks!
I think I'll make an issue about getting a spinner on the search page/error toasts if it fails.
