### ISSUE TITLE
Don't mark upcoming episodes as watched

### ISSUE THREAD

**Issue by watashibeme** [red-coracle/episodes#56]
Describe the **issue:**
When clicking "mark season as watched" it marks upcoming episodes and TBAs too
**Expected** **behaviour:**
When an epsiode isn't available you shouldn't be able to mark it as watched because its not aired or its state isn't known
**Suggestion:**
TBAs or upcomings could be grayed out
Its prefered that they are disabled from altering their state(watched or unwatched)
When refreshing show data, don't fetch unaired episodes
Also its possible to add an option to hide unaired episodes and... A lot more 
**Why don't you do it yourself then mr-know-it-all??!**
Thank you:)
I dont't have a computer I sold it quite some while ago which was a mistake :(
Extra details:
Android:AICP 15.0(Android 10)
Episodes version:0.13.6(latest-fdroid)

**Comment by watashibeme** [comment]
why, yes, thank you!

**Comment by SebiderSushi** [comment]
Thanks a lot for your response. That helps and is good enough for my case.
