### ISSUE TITLE
Episode info not updating

### ISSUE THREAD

**Issue by CracktheDom** [red-coracle/episodes#79]
Using version 0.15.0 on Android 11. Connection to the repository, TMdb, does not seem to be working. Existing entries in my database are not being updated, and whenever I search for new shows, the app states that no search results were found.

**Comment by red-coracle** [comment]
I don't have an Android 11 device right now, but version 0.15.0 still uses TVDB (unless you built off the `tmdb` branch) and is still working for me on both Android 10 and 12. Do you have a different network you can try (e.g. cellular instead of WiFi) or the ability to get logs from ADB?

**Comment by CracktheDom** [comment]
I have tried connecting via WiFi and a cellular network. The result is the
same, no updates or search results.

**Comment by CracktheDom** [comment]
I have access to adb, can you tell me where the logs are located?

**Comment by red-coracle** [comment]
I usually just do `adb logcat`, wait for the output to settle, perform the action (e.g. update a show), and then Ctrl-C to stop.

**Comment by CracktheDom** [comment]
Is there way to narrow the output from logcat to what is relevant with your app?

**Comment by CracktheDom** [comment]
These two errors/exceptions kept recurring while trying to refresh a show: 
java.net.ConnectException: Failed to connect to api.thetvdb.com/13.249.50.100:443
Caused by: java.net.ConnectException: Failed to connect to api.thetvdb.com/13.249.50.100/443 from 10.0.0.2 (port 43726) after 10000ms: isConnect failed: ECON REFUSED (Connection refused)

**Comment by red-coracle** [comment]
I don't think it's an issue from the app specifically. It's basically saying that the TVDB API server is refusing your connection. Maybe it's a transient/regional outage? I tried connecting to that IP address from a few VPN locations and they all worked.

`curl --resolve api.thetvdb.com:443:13.249.50.100 -X POST --data '{"apikey": "E457AE7B767BC9F4"}' -H 'Content-Type: application/json' https://api.thetvdb.com/login`
