### ISSUE TITLE
[bug] Show isn't added to library

### ISSUE THREAD

**Issue by ekogupta** [red-coracle/episodes#92]
Hello,
Thanks for the app!
I am trying to add a specific [tv show](https://thetvdb.com/series/deus-cerebro) to the library, but the app doesn't add it.
I get the initial "Adding [show name] to the library" prompt, but not the concluded prompt.
Using version 0.15.1 (Commit 75a0a40) on Android 11.

**Comment by red-coracle** [comment]
Thanks for the report! It appears to me that TheTVDB may have finally cut off access for legacy API keys. I've already made the changes to use TMDB instead and will cut a release for that. The metadata is sometimes slightly different and the banners aren't quite as nice, but free is free 🤷‍♂️.

**Comment by ekogupta** [comment]
I tested adding other random shows and the app adds them, just not that particular one.
I'll test the new version you've released once it's released on F-Droid. Thank you!

**Comment by red-coracle** [comment]
How odd - when I tried connecting to TheTVDB yesterday it was erroring out, but seems find now. Regardless, I tested that show with the TMDB version and it adds correctly.

**Comment by ekogupta** [comment]
Spoke too soon... I have tried the new version and can confirm that the show in question adds perfectly to library.
