### ISSUE TITLE
[improve] Starred shows do not behave the same on v0.16.0

### ISSUE THREAD

**Issue by ekogupta** [red-coracle/episodes#96]
In previous versions, starred shows appeared on top of the lists. 
I used this feature to organize shows that I'm currently watching on the Underway tab.
However, this does not happen on v0.16.0.

**Comment by onchov** [comment]
FWIW, with my eyesight I didn't even see the buttons, accidentally archived a programme twice, found the 'archived' list but had no idea how to unarchive. Only after reading the issue description above I found out how it's working.

**Comment by red-coracle** [comment]
> In previous versions, starred shows appeared on top of the lists.

Thanks, it's fixed by 006e24dbae85b3283b93fd236987c2e86c203f46

> FWIW, with my eyesight I didn't even see the buttons, accidentally archived a programme twice

I've honestly been thinking of removing the archived button and adding it to the menu instead, since I feel it's less common to archive a show. Otherwise I would probably need to come up with new artwork to make it more visible.
